default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ship_development

ship:
  <<: *default
  database: ship_test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: ship_production
  username: ship
  password: <%= ENV["POSTGRES_PASSWORD"] %>
