service: ship
image: jeromedalbert/ship

servers:
  web:
  - <%= ENV['SERVER_IP'] %>

registry:
  username: jeromedalbert
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - SERVER_IP

accessories:
  db:
    image: postgres:15
    host: <%= ENV['SERVER_IP'] %>
    port: 5432
    env:
      clear:
        POSTGRES_USER: ship
        POSTGRES_DB: ship_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

healthcheck:
  max_attempts: 10
