service: ship
image: jeromedalbert/ship
servers:
  - 143.198.234.99
registry:
  username: jeromedalbert
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
healthcheck:
  max_attempts: 10
